# 7 - Filtragem de dados
Filtragem de dados é uma tarefa importantíssima na vida de qualquer cientista de dados. Nessa seção, veremos como criar filtros em um conjunto de dados utilizando o Pandas.

## Operadores booleanos

### and

and é operador lógico no qual a resposta da operação é verdade se ambas as variáveis de entrada forem verdade.

In [ ]:
x = 12

In [ ]:
x > 5 and x < 15

True

### or

or é operador lógico no qual a resposta da operação é verdade se pelo menos uma das variáveis de entrada for verdade.

In [ ]:
y = 5

In [ ]:
y < 7 or y > 13

True

### not

not é o operador lógico de negação

In [ ]:
not True

False

In [ ]:
not False

True

### Numpy

Definindo dois array diferentes, depois fazendo a divisão de um pelo outro ao quadrado.

In [ ]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Quais indices apresentam um número maior que 21, o operador retorna uma array com true ou false de acordo com cada indice do array que corresponde á inferência lógica.

In [ ]:
bmi > 21

array([ True, False,  True,  True,  True])

Testa se todos os elementos da matriz ao longo de um determinado eixo corresponde a inferência lógica. Nesse caso esta sendo verificado se todos os números estão no intevelo de 21 a 22.

In [ ]:
bmi.all() > 21 and bmi.all() < 22

False

Nesse caso esta sendo verificado se todos os números estão no intevelo de 21 a 22. E o retorno é de acordo com o indice e mostra se o número correspondente do array está ou não de acordo com a inferência lógica.

In [ ]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

Nesse caso esta sendo verificado se todos os números estão no intevelo de 21 a 22. E o retorno são os números do array que estão de acordo com a inferência lógica.

In [ ]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## Filtrando um DataFrame Pandas

Carregando e mostrando os dados do arquivo .csv

In [ ]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col=0)
brics

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

**Objetivo**: selecionar os países com área maior do que 8 milhões de km2

3 passos:
- Selecionar a coluna "area"
- Fazer uma comparação na coluna "area"
- Usar o resultado para selecionar os países

In [ ]:
# Selecionar a coluna "area"
brics['area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
# Fazer uma comparação na coluna "area"
brics['area'] > 8
is_huge = brics['area'] > 8
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
# Usar o resultado para selecionar os países
brics[is_huge]

   country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
# Importando dataset de carros
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [ ]:
# Extraia a coluna 'drives_right' do DataFrame 'cars' e atribua a variável 'dr'
dr = cars['drives_right']

# Use a variável 'dr' para criar um subconjunto de dados chamado 'sel'
sel = cars[dr]

# Imprima a variável 'sel'
print(sel)

     cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [ ]:
# Crie uma variável car_maniac: linhas que possuem 'cars_per_cap' maiores do que 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Imprima 'car_maniac'
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [ ]:
# Importe o conjunto de dados 'cars.csv', bem como as bibliotecas 'pandas' e 'numpy'
import pandas as pd
import numpy as np
cars = pd.read_csv('cars.csv', index_col = 0)

# Crie a variável 'medium': linhas que possuem 'cars_per_cap' entre 100 e 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Imprima 'medium'
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True